"""Generate a tiny disc backup and optionally convert it with the real workflow.

All pictures and sounds are generated by FFmpeg; no commercial media is used.
Existing demo destinations are refused. DVD authoring uses dvdauthor in WSL.
"""
from __future__ import annotations
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BD = (ROOT / "bd2hevc_app").is_dir()


def run(command, log):
    with log.open("ab") as output:
        result = subprocess.run([str(item) for item in command], stdout=output, stderr=subprocess.STDOUT,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    if result.returncode:
        raise RuntimeError(f"Command failed ({result.returncode}); see {log}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("destination", type=Path, help="New, empty demo directory")
    parser.add_argument("--convert", action="store_true")
    parser.add_argument("--encoder", default="libx265", choices=["libx265", "hevc_nvenc", "hevc_qsv", "hevc_amf"])
    parser.add_argument("--tsmuxer", type=Path)
    parser.add_argument("--vlc-root", type=Path)
    parser.add_argument("--output-format",choices=('uhd-bd','dvd-hevc'),default='uhd-bd',help='DVD output format')
    args = parser.parse_args()
    directory = args.destination.resolve()
    directory.mkdir(parents=True, exist_ok=False)
    os.environ["BD2HEVC_STATE_DIR" if BD else "DVD2HEVC_STATE_DIR"] = str(directory / "state")
    log = directory / "generation.log"
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg: raise RuntimeError("FFmpeg is required on PATH")
    source = directory / ("Colour Lab (BD)" if BD else "Colour Lab (DVD).iso")
    output = directory / ("Colour Lab (BD) (HEVC).iso" if BD else ("Colour Lab (DVD) (UHD-BD).iso" if args.output_format == 'uhd-bd' else "Colour Lab (DVD) (HEVC).iso"))
    inputs = [ffmpeg, "-hide_banner", "-nostdin", "-f", "lavfi", "-i",
              "testsrc2=size=1280x720:rate=24" if BD else "testsrc2=size=720x576:rate=25",
              "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000", "-t", "16"]
    if BD:
        tsmuxer = args.tsmuxer or shutil.which("tsMuxeR") or ROOT / "tools/tsmuxer/tsmuxer.exe"
        if not Path(tsmuxer).is_file(): raise RuntimeError("Use --tsmuxer with a tsMuxeR executable")
        os.environ["PATH"] = str(Path(tsmuxer).resolve().parent) + os.pathsep + os.environ.get("PATH", "")
        video, audio = directory / "generated.h264", directory / "generated.ac3"
        run(inputs + ["-an", "-c:v", "libx264", "-preset", "fast", "-pix_fmt", "yuv420p", "-b:v", "5000k",
            "-maxrate", "8000k", "-bufsize", "8000k", "-x264-params", "bluray-compat=1:open-gop=0:keyint=24",
            "-color_primaries", "bt709", "-color_trc", "bt709", "-colorspace", "bt709", video], log)
        run([ffmpeg,"-hide_banner","-nostdin","-f","lavfi","-i","sine=frequency=440:sample_rate=48000",
             "-t","16","-c:a","ac3","-ac","2","-b:a","192k",audio], log)
        meta = directory / "source.meta"
        meta.write_text(f'MUXOPT --blu-ray --vbr\nV_MPEG4/ISO/AVC, "{video}", fps=24\nA_AC3, "{audio}", lang=eng\n', encoding="utf-8")
        run([tsmuxer, meta, source], log)
        command = [sys.executable, ROOT / "bd2hevc.py", "auto", source, output, "--encoder", args.encoder,
            "--output-format", "iso", "--no-makemkv", "--decode-sample", "3", "--report", directory / "conversion.json"]
    else:
        mpg = directory / "generated.mpg"
        run(inputs + ["-target","pal-dvd","-aspect","16:9","-b:v","5000k","-ac","2",mpg], log)
        converted_path = subprocess.check_output(["wsl","--exec","wslpath","-a",directory.as_posix()], text=True,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0)).strip()
        xml = directory / "dvd.xml"
        xml.write_text(f'<dvdauthor dest="{converted_path}/source"><vmgm><menus><video format="pal" /></menus></vmgm>'
            f'<titleset><titles><video format="pal" aspect="16:9"/><audio format="ac3" lang="en"/>'
            f'<pgc><vob file="{converted_path}/generated.mpg" chapters="0,8"/></pgc></titles></titleset></dvdauthor>', encoding="utf-8")
        run(["wsl","--exec","dvdauthor","-x",converted_path + "/dvd.xml"], log)
        run(["wsl","--exec","genisoimage","-dvd-video","-udf","-V","COLOUR_LAB","-o",converted_path + "/" + source.name,
             converted_path + "/source"], log)
        command = [sys.executable, ROOT / "dvd2hevc.py", "auto", source, output, "--encoder", args.encoder,
                   "--encoder-preset","p1","--deinterlace","off","--work-dir",directory / "conversion-work",
                   "--output-format",args.output_format]
        if args.vlc_root: command += ["--vlc-root", args.vlc_root]
        if args.tsmuxer: command += ["--tsmuxer",args.tsmuxer]
    if args.convert:
        started = time.monotonic()
        run(command, directory / "conversion.log")
        result = {"generated_media":True,"project":"BD2HEVC" if BD else "DVD2HEVC", "encoder":args.encoder,
            "output_format": "iso" if BD else args.output_format,
            "duration_seconds":16,"source_bytes":sum(p.stat().st_size for p in source.rglob("*") if p.is_file()) if BD else source.stat().st_size,
            "output_bytes":output.stat().st_size,"elapsed_seconds":round(time.monotonic()-started,2),"outcome":"passed"}
        (directory / "demo-result.json").write_text(json.dumps(result,indent=2),encoding="utf-8")
        print(json.dumps(result,indent=2))
    else: print("Generated backup:", source)


if __name__ == "__main__": main()
